In [1]:
import numpy as np
import pandas as pd
import pyarrow as pa

Conveorting Pandas Dataframe to Apache Arrow Table

In [2]:
df = pd.DataFrame({'one': [20, np.nan, 2.5],'two': ['january', 'february', 'march'],'three': [True, False, True]},index=list('abc'))
table = pa.Table.from_pandas(df)

C:\Users\Administrator\Anaconda3\envs\work1\lib\site-packages\pyarrow\pandas_compat.py:114: FutureWarning: A future version of pandas will default to `skipna=True`. To silence this warning, pass `skipna=True|False` explicitly.
  result = infer_dtype(pandas_collection)

Pyarrow Table to Pandas Data Frame

In [3]:
df_new = table.to_pandas()

C:\Users\Administrator\Anaconda3\envs\work1\lib\site-packages\pyarrow\pandas_compat.py:708: FutureWarning: .labels was deprecated in version 0.24.0. Use .codes instead.
  labels = getattr(columns, 'labels', None) or [
C:\Users\Administrator\Anaconda3\envs\work1\lib\site-packages\pyarrow\pandas_compat.py:735: FutureWarning: the 'labels' keyword is deprecated, use 'codes' instead
  return pd.MultiIndex(levels=new_levels, labels=labels, names=columns.names)
C:\Users\Administrator\Anaconda3\envs\work1\lib\site-packages\pyarrow\pandas_compat.py:752: FutureWarning: .labels was deprecated in version 0.24.0. Use .codes instead.
  labels, = index.labels

Read CSV

In [4]:
from pyarrow import csv
fn = 'data.csv'
table = csv.read_csv(fn)
df = table.to_pandas()

Writing a parquet file from Apache Arrow

In [5]:
import pyarrow.parquet as pq
pq.write_table(table, 'example.parquet')

Reading a parquet file

In [6]:
table2 = pq.read_table('example.parquet')
table2

pyarrow.Table
no: int64
tv: double
radio: double
newspaper: double
sales: double

Reading some columns from a parquet file

In [7]:
table2 = pq.read_table('example.parquet', columns=['one', 'three'])

Transforming Parquet file into a Pandas DataFrame

In [8]:
pdf = pq.read_pandas('example.parquet', columns=['two']).to_pandas()
pdf

Empty DataFrame
Columns: []
Index: []

Avoiding pandas index

In [9]:
table = pa.Table.from_pandas(df, preserve_index=False)
pq.write_table(table, 'example_noindex.parquet')
t = pq.read_table('example_noindex.parquet')
t.to_pandas()

      no     tv  radio  newspaper  sales
0      1  230.1   37.8       69.2   22.1
1      2   44.5   39.3       45.1   10.4
2      3   17.2   45.9       69.3    9.3
3      4  151.5   41.3       58.5   18.5
4      5  180.8   10.8       58.4   12.9
..   ...    ...    ...        ...    ...
195  196   38.2    3.7       13.8    7.6
196  197   94.2    4.9        8.1    9.7
197  198  177.0    9.3        6.4   12.8
198  199  283.6   42.0       66.2   25.5
199  200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

Check metadata

In [10]:
parquet_file = pq.ParquetFile('example.parquet')
parquet_file.metadata

<pyarrow._parquet.FileMetaData object at 0x0000000007D9ECC8>
  created_by: parquet-cpp version 1.5.1-SNAPSHOT
  num_columns: 5
  num_rows: 200
  num_row_groups: 1
  format_version: 1.0
  serialized_size: 550

See data schema

In [11]:
parquet_file.schema

<pyarrow._parquet.ParquetSchema object at 0x0000000007E074C8>
no: INT64
tv: DOUBLE
radio: DOUBLE
newspaper: DOUBLE
sales: DOUBLE

In memory

In [12]:
writer = pa.BufferOutputStream()
writer.write(b'hello, friends')
buf = writer.getvalue()
print(buf)
print(buf.size)

<pyarrow.lib.Buffer object at 0x0000000007E067F0>
14

In [19]:
reader = pa.BufferReader(buf)
reader.seek(0)
reader.read(14)

b'hello, friends'